version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/inventory-app"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/inventory-app/server"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/inventory-app/desktop"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "/inventory-app/android"
    schedule:
      interval: "weekly"
